config/routes.rb
Rails.application.routes.draw do
    post 'register', to: 'authentications#register'
    post 'login', to: 'authentications#login'
    resources :colours
    resources :sounds, only: [:index, :show]
    resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/colour.rb
class Colour < ApplicationRecord
  belongs_to :sound
  belongs_to :user
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  has_many :colours
  belongs_to :sounds
end

app/models/sound.rb
class Sound < ApplicationRecord
  has_many :colours
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  has_many :colours
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  before_action :authenticate_user!

  def authenticate_user!
    render json: { errors: ["Unauthorized"] }, status: 401 unless user_signed_in?
  end

  def user_signed_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find(decoded_token[:id]) if id_found?
  rescue
    nil
  end

  private

    def id_found?
      token && decoded_token && decoded_token[:id]
    end

    def decoded_token
      @decoded_token ||= Auth.decode(token) if token
    end

    def token
      @token ||= if request.headers['Authorization'].present?
        request.headers['Authorization'].split.last
      end
    end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  skip_before_action :authenticate_user!

  def register
    user = User.new(user_params)
    if user.save
      token = Auth.issue({id: user.id})
      render json: { token: token, user: UserSerializer.new(user) }, status: :ok
    else
      render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def login
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      token = Auth.issue({id: user.id})
      render json: { token: token, user: UserSerializer.new(user) }, status: :ok
    else
      render json: { errors: ["Invalid login credentials."]}, status: 401
    end
  end

  private
    def user_params
      hash = {}
      hash.merge! params.slice(:email, :password, :password_confirmation)
      hash
    end
end

app/controllers/colours_controller.rb
class ColoursController < ApplicationController
  before_action :set_colour, only: [:show, :update, :destroy]

  # GET /colours
  def index
    @colours = Colour.all

    render json: @colours
  end

  # GET /colours/1
  def show
    render json: @colour
  end

  # POST /colours
  def create
    @colour = current_user.colours.new(colour_params)

    if @colour.save
      render json: @colour, status: :created, location: @colour
    else
      render json: @colour.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /colours/1
  def update
    if @colour.update(colour_params)
      render json: @colour
    else
      render json: @colour.errors, status: :unprocessable_entity
    end
  end

  # DELETE /colours/1
  def destroy
    @colour.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colour
      @colour = Colour.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def colour_params
      params.require(:colour).permit(:sound_id, :name, :user_id)
    end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :update, :destroy]

  # GET /results
  def index
    @results = Result.all

    render json: @results
  end

  # GET /results/1
  def show
    render json: @result
  end

  # POST /results
  def create
    @result = Result.new(result_params)

    if @result.save
      render json: @result, status: :created, location: @result
    else
      render json: @result.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /results/1
  def update
    if @result.update(result_params)
      render json: @result
    else
      render json: @result.errors, status: :unprocessable_entity
    end
  end

  # DELETE /results/1
  def destroy
    @result.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def result_params
      params.require(:result).permit(:sounds, :colours)
    end
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  before_action :set_sound, only: [:show, :edit, :update, :destroy]

  # GET /sounds
  # GET /sounds.json
  def index
    @sounds = Sound.all

    render json: @sounds
  end

  # GET /sounds/1
  # GET /sounds/1.json
  def show
    render json: @sound
  end

  # # GET /sounds/new
  # def new
  #   @sound = Sound.new
  # end

  # GET /sounds/1/edit
  def edit
  end

  # POST /sounds
  # POST /sounds.json
  def create
    @sound = Sound.new(sound_params)

    respond_to do |format|
      if @sound.save
        format.html { redirect_to @sound, notice: 'Sound was successfully created.' }
        format.json { render :show, status: :created, location: @sound }
      else
        format.html { render :new }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sounds/1
  # PATCH/PUT /sounds/1.json
  def update
    respond_to do |format|
      if @sound.update(sound_params)
        format.html { redirect_to @sound, notice: 'Sound was successfully updated.' }
        format.json { render :show, status: :ok, location: @sound }
      else
        format.html { render :edit }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sounds/1
  # DELETE /sounds/1.json
  def destroy
    @sound.destroy
    respond_to do |format|
      format.html { redirect_to sounds_url, notice: 'Sound was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sound
      @sound = Sound.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sound_params
      params.require(:sound).permit(:name, :audio, :genre)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  # GET /users/1
  def show
    render json: @user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/views/sounds/_form.html.erb
<%= form_for(sound) do |f| %>
  <% if sound.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sound.errors.count, "error") %> prohibited this sound from being saved:</h2>

      <ul>
      <% sound.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_area :type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sounds/edit.html.erb
<h1>Editing Sound</h1>

<%= render 'form', sound: @sound %>

<%= link_to 'Show', @sound %> |
<%= link_to 'Back', sounds_path %>

app/views/sounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sounds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sounds.each do |sound| %>
      <tr>
        <td><%= sound.name %></td>
        <td><%= sound.type %></td>
        <td><%= link_to 'Show', sound %></td>
        <td><%= link_to 'Edit', edit_sound_path(sound) %></td>
        <td><%= link_to 'Destroy', sound, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sound', new_sound_path %>

app/views/sounds/new.html.erb
<h1>New Sound</h1>

<%= render 'form', sound: @sound %>

<%= link_to 'Back', sounds_path %>

app/views/sounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sound.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @sound.type %>
</p>

<%= link_to 'Edit', edit_sound_path(@sound) %> |
<%= link_to 'Back', sounds_path %>